version: '3'
services:
  mlflow:
    build:
      context: .
      dockerfile: MLFlow-Dockerfile
    image: mlflow
    container_name: mlflow
    volumes:
      - ./catboost_info:/hurb-ml-challenge/catboost_info
      - ./mlruns:/hurb-ml-challenge/mlruns
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0

  bento-api:
    build: .
    image: bento-api
    container_name: bento-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mlflow